version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: guss-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: guss
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend1:
    image: guss-backend
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  backend2:
    image: guss-backend
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  backend3:
    image: guss-backend
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: