### Create round
POST http://localhost:3001/rounds
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "startAt": "2025-06-19T07:33:00.000Z",
  "duration": 30
}

### Get rounds
GET http://localhost:3000/rounds
Authorization: Bearer {{jwt}}


### Get round info
GET http://localhost:3000/rounds/{{roundId}}
Authorization: Bearer {{jwt}}

### Handle tap
POST http://localhost:3000/rounds/{{roundId}}/tap
Authorization: Bearer {{jwt}}

